name: Run tests
run-name: ${{ github.actor }} is running unit tests via GitHub Actions 🚀
on: [ push ]
jobs:
  Cargo-Tests:
    runs-on: rust
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: current=$PWD; for line in $(find . -name Cargo.toml); do; cd ${line//Cargo.toml/}; cargo test; cd $current ; done
